version: "3.9"
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestiondeseleves
    container_name: amadouguindo
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kalanblowdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Homeboarding2008&
  postgres:
    image: 'postgres:15-alpine'
    restart: always
    container_name: postgres-15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    #env_file:
     # - .env # Reference to the .env file
