services:
  eureka-server:
    build:
      context: ../Kalanblow-discovery-service  # Répertoire où se trouve le Dockerfile du Discovery Server
    volumes:
      - ./logs/Kalanblow-discovery-service/:/app/Kalanblow-discovery-service/logs
    ports:
      - "8761:8761" # Mapping 8761 (host) vers 8761 (container)
    networks:
      - gestiondesincriptions-network
      - gestiondescours-network
    environment:
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
      - eureka.server.enable-self-preservation=false

    #  - microservice2

  gestiondesincriptions:
    build:
      context: ../GestionDesEleves  # Répertoire du microservice 1
    ports:
      - "8082:8080" #Mapping 8082 (host) vers 8080 (container:gestiondesincriptions expose le port 8081 à l'intérieur du conteneur)
    networks:
      - gestiondesincriptions-network
      - gestiondescours-network
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.application.name=microservice1
    depends_on:
      - eureka-server

  gestiondescours:
    build:
      context: ../gestiondescours  # Répertoire du microservice 2
    ports:
      - "8081:8080"
    networks:
      - gestiondescours-network
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.application.name=microservice2
    depends_on:
      - eureka-server

networks:
  gestiondesincriptions-network:
  gestiondescours-network:
    driver: bridge
