name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construire l'image Docker
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gestiondesincriptions:latest

      # Étape 4 : Pousser l'image vers Docker Hub
      - name: Push Docker image
        run: docker push gestiondesincriptions:latest

